#include "cpu.h"
#include "memory/guest_memory.h"
#include <cstdint>
#include <iostream>
CPU::CPU(GuestMemory& m):memory_(m){reset();}
void CPU::reset(){registers_.fill(0);rip_=0;rflags_=0;lastError_=nullptr;halted_=false;framePresented_=false;exitCode_=0;guestTitle_.clear();}
std::uint64_t CPU::getRegister(Register r)const{return registers_[r];} void CPU::setRegister(Register r,std::uint64_t v){registers_[r]=v;}
std::uint64_t CPU::rip()const{return rip_;} void CPU::setRip(std::uint64_t v){rip_=v;} std::uint64_t CPU::rflags()const{return rflags_;}
const char* CPU::lastError()const{return lastError_;} bool CPU::halted()const{return halted_;} std::int64_t CPU::exitCode()const{return exitCode_;}
bool CPU::framePresented()const{return framePresented_;} void CPU::clearFramePresented(){framePresented_=false;} const std::string& CPU::guestTitle()const{return guestTitle_;}
bool CPU::fail(const char*m){lastError_=m;return false;}
bool CPU::fetch8(std::uint8_t&v){if(!memory_.read8(rip_,v))return fail("instruction fetch failed");++rip_;return true;}
bool CPU::fetch32(std::uint32_t&v){if(!memory_.read32(rip_,v))return fail("instruction fetch failed");rip_+=4;return true;}
bool CPU::fetch64(std::uint64_t&v){if(!memory_.read64(rip_,v))return fail("instruction fetch failed");rip_+=8;return true;}
bool CPU::decodeModRM(std::uint8_t v,ModRM&m)const{m.mod=v>>6;m.reg=(v>>3)&7;m.rm=v&7;return true;}
std::size_t CPU::extendedRegister(std::uint8_t i,std::uint8_t b)const{return i+(b?8:0);}
bool CPU::resolveModRMAddress(const ModRM&m,std::uint8_t rex,std::uint64_t&a){if(m.mod==3)return fail("ModRM operand is a register, not memory");if(m.rm==4){std::uint8_t s;if(!fetch8(s))return false;const std::uint64_t sc=1ull<<((s>>6)&3);const std::uint8_t ix=(s>>3)&7;const std::uint8_t ba=s&7;const bool hi=!(ix==4&&!(rex&2));std::int64_t d=0;bool hb=true;if(m.mod==0&&ba==5){hb=false;std::uint32_t x;if(!fetch32(x))return false;d=(std::int32_t)x;}else if(m.mod==1){std::uint8_t x;if(!fetch8(x))return false;d=(std::int8_t)x;}else if(m.mod==2){std::uint32_t x;if(!fetch32(x))return false;d=(std::int32_t)x;}std::int64_t e=d;if(hb)e+=(std::int64_t)registers_[extendedRegister(ba,rex&1)];if(hi)e+=(std::int64_t)(registers_[extendedRegister(ix,(rex>>1)&1)]*sc);a=(std::uint64_t)e;return true;}std::int64_t d=0;if(m.mod==0&&m.rm==5){std::uint32_t x;if(!fetch32(x))return false;d=(std::int32_t)x;a=(std::uint64_t)((std::int64_t)rip_+d);return true;}if(m.mod==1){std::uint8_t x;if(!fetch8(x))return false;d=(std::int8_t)x;}else if(m.mod==2){std::uint32_t x;if(!fetch32(x))return false;d=(std::int32_t)x;}a=(std::uint64_t)((std::int64_t)registers_[extendedRegister(m.rm,rex&1)]+d);return true;}
bool CPU::readModRMR64(const ModRM&m,std::uint8_t rex,std::uint64_t&v){if(m.mod==3){v=registers_[extendedRegister(m.rm,rex&1)];return true;}std::uint64_t a;if(!resolveModRMAddress(m,rex,a))return false;if(!memory_.read64(a,v))return fail("64-bit memory read failed");return true;}
bool CPU::writeModRMR64(const ModRM&m,std::uint8_t rex,std::uint64_t v){if(m.mod==3){registers_[extendedRegister(m.rm,rex&1)]=v;return true;}std::uint64_t a;if(!resolveModRMAddress(m,rex,a))return false;if(!memory_.write64(a,v))return fail("64-bit memory write failed");return true;}
void CPU::updateAddFlags(std::uint64_t a,std::uint64_t b,std::uint64_t r){rflags_&=~(CarryFlag|ZeroFlag|SignFlag|OverflowFlag);if(r<a)rflags_|=CarryFlag;if(!r)rflags_|=ZeroFlag;if(r>>63)rflags_|=SignFlag;if((a>>63)==(b>>63)&&(a>>63)!=(r>>63))rflags_|=OverflowFlag;}
void CPU::updateSubFlags(std::uint64_t a,std::uint64_t b,std::uint64_t r){rflags_&=~(CarryFlag|ZeroFlag|SignFlag|OverflowFlag);if(a<b)rflags_|=CarryFlag;if(!r)rflags_|=ZeroFlag;if(r>>63)rflags_|=SignFlag;if((a>>63)!=(b>>63)&&(a>>63)!=(r>>63))rflags_|=OverflowFlag;}
bool CPU::handleSyscall(){auto n=registers_[RAX];if(n==1){auto fd=registers_[RDI],a=registers_[RSI],l=registers_[RDX];if(fd!=1&&fd!=2){registers_[RAX]=(std::uint64_t)-9;return true;}if(l>1024*1024)return fail("guest write is too large");for(std::uint64_t i=0;i<l;i++){std::uint8_t b;if(!memory_.read8(a+i,b))return fail("guest write read failed");std::cout.put((char)b);}std::cout.flush();registers_[RAX]=l;return true;}if(n==200){framePresented_=true;registers_[RAX]=0;return true;}if(n==201){auto a=registers_[RSI],l=registers_[RDX];if(l>512)return fail("guest title is too long");guestTitle_.clear();for(std::uint64_t i=0;i<l;i++){std::uint8_t b;if(!memory_.read8(a+i,b))return fail("guest title read failed");if(b==0)break;guestTitle_.push_back((char)b);}registers_[RAX]=guestTitle_.size();return true;}if(n==60){exitCode_=(std::int64_t)registers_[RDI];halted_=true;return true;}return fail("unsupported guest syscall");}
bool CPU::step(){if(halted_)return true;lastError_=nullptr;std::uint8_t op;if(!fetch8(op))return false;if(op==0x90)return true;std::uint8_t rex=0;while((op&0xf0)==0x40){rex=op&0xf;if(!fetch8(op))return false;}
if(!(rex&8)&&op>=0xb8&&op<=0xbf){std::uint32_t x;if(!fetch32(x))return false;registers_[extendedRegister(op-0xb8,rex&1)]=x;return true;}if((rex&8)&&op>=0xb8&&op<=0xbf){std::uint64_t x;if(!fetch64(x))return false;registers_[extendedRegister(op-0xb8,rex&1)]=x;return true;}
if(op==0xc7){std::uint8_t q;if(!fetch8(q))return false;ModRM m;decodeModRM(q,m);if(m.reg!=0)return fail("unsupported C7 operation");std::uint32_t imm;if(!fetch32(imm))return false;const std::uint64_t v=(rex&8)?static_cast<std::uint64_t>(static_cast<std::int64_t>(static_cast<std::int32_t>(imm))):imm;if(m.mod==3){registers_[extendedRegister(m.rm,rex&1)]=v;return true;}return writeModRMR64(m,rex,v);}
if(op>=0x50&&op<=0x57){auto r=extendedRegister(op-0x50,rex&1),s=registers_[RSP]-8;if(!memory_.write64(s,registers_[r]))return fail("stack push failed");registers_[RSP]=s;return true;}if(op>=0x58&&op<=0x5f){auto r=extendedRegister(op-0x58,rex&1),s=registers_[RSP];std::uint64_t v;if(!memory_.read64(s,v))return fail("stack pop failed");registers_[r]=v;registers_[RSP]=s+8;return true;}
if(rex&8){if(op==0x8d){std::uint8_t q;if(!fetch8(q))return false;ModRM m;decodeModRM(q,m);if(m.mod==3)return fail("LEA requires memory operand");std::uint64_t a;if(!resolveModRMAddress(m,rex,a))return false;registers_[extendedRegister(m.reg,(rex>>2)&1)]=a;return true;}if(op==0x89||op==0x8b){std::uint8_t q;if(!fetch8(q))return false;ModRM m;decodeModRM(q,m);auto r=extendedRegister(m.reg,(rex>>2)&1);if(op==0x89)return writeModRMR64(m,rex,registers_[r]);std::uint64_t v;if(!readModRMR64(m,rex,v))return false;registers_[r]=v;return true;}if(op==0x01||op==0x29||op==0x39){std::uint8_t q;if(!fetch8(q))return false;ModRM m;decodeModRM(q,m);auto r=extendedRegister(m.reg,(rex>>2)&1);std::uint64_t a;if(!readModRMR64(m,rex,a))return false;auto b=registers_[r];if(op==0x01){auto v=a+b;if(!writeModRMR64(m,rex,v))return false;updateAddFlags(a,b,v);}else if(op==0x29){auto v=a-b;if(!writeModRMR64(m,rex,v))return false;updateSubFlags(a,b,v);}else updateSubFlags(a,b,a-b);return true;}if(op==0x21||op==0x09||op==0x31){std::uint8_t q;if(!fetch8(q))return false;ModRM m;decodeModRM(q,m);auto r=extendedRegister(m.reg,(rex>>2)&1);std::uint64_t a;if(!readModRMR64(m,rex,a))return false;auto b=registers_[r],v=op==0x21?a&b:op==0x09?a|b:a^b;if(!writeModRMR64(m,rex,v))return false;rflags_&=~(CarryFlag|OverflowFlag|ZeroFlag|SignFlag);if(!v)rflags_|=ZeroFlag;if(v>>63)rflags_|=SignFlag;return true;}}
if(op==0x83){std::uint8_t q,i;if(!fetch8(q)||!fetch8(i))return false;ModRM m;decodeModRM(q,m);if(m.reg!=0)return fail("unsupported 83 operation");std::uint64_t a;if(!readModRMR64(m,rex,a))return false;auto b=(std::uint64_t)(std::int64_t)(std::int8_t)i,v=a+b;if(!writeModRMR64(m,rex,v))return false;updateAddFlags(a,b,v);return true;}
if(op==0xff){std::uint8_t q;if(!fetch8(q))return false;ModRM m;decodeModRM(q,m);if(m.reg!=1)return fail("unsupported FF operation");std::uint64_t a;if(!readModRMR64(m,rex,a))return false;auto v=a-1;if(!writeModRMR64(m,rex,v))return false;updateSubFlags(a,1,v);return true;}
if(op==0x0f){std::uint8_t s;if(!fetch8(s))return false;if(s==5)return handleSyscall();return fail("unsupported 0F opcode");}if(op==0xeb){std::uint8_t d;if(!fetch8(d))return false;rip_+=(std::int64_t)(std::int8_t)d;return true;}if(op==0x74||op==0x75){std::uint8_t d;if(!fetch8(d))return false;bool z=rflags_&ZeroFlag;if((op==0x74?z:!z))rip_+=(std::int64_t)(std::int8_t)d;return true;}if(op==0xe8){std::uint32_t d;if(!fetch32(d))return false;auto ret=rip_,t=(std::uint64_t)((std::int64_t)rip_+(std::int32_t)d),s=registers_[RSP]-8;if(!memory_.write64(s,ret))return fail("call stack write failed");registers_[RSP]=s;rip_=t;return true;}if(op==0xc3){auto s=registers_[RSP];std::uint64_t r;if(!memory_.read64(s,r))return fail("return stack read failed");registers_[RSP]=s+8;rip_=r;return true;}return fail("unsupported opcode");}
