#include "cpu/cpu.h"
#include "elf_loader.h"
#include "memory/guest_memory.h"
#include "renderer.h"
#include "window.h"
#include "appx/appx_loader.h"
#include "input/input_abi.h"
#include <chrono>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <thread>
#include <vector>

static bool readFile(const std::string& path,std::vector<std::uint8_t>& image){std::ifstream file(path,std::ios::binary|std::ios::ate);if(!file){std::cerr<<"File open failed: "<<path<<'\n';return false;}auto size=file.tellg();if(size<0)return false;image.resize(static_cast<std::size_t>(size));file.seekg(0);return image.empty()||static_cast<bool>(file.read(reinterpret_cast<char*>(image.data()),static_cast<std::streamsize>(image.size())));}

static bool loadGuest(const std::vector<std::uint8_t>& image,bool graphics,GuestMemory& memory,CPU& cpu){constexpr std::uint64_t fb=0x800000,fbMapSize=0x50000,stackBase=0x3f00000,stackSize=0x100000,stackTop=stackBase+stackSize;if(graphics&&!memory.map(fb,fb,fbMapSize,GuestMemory::Permissions::Read|GuestMemory::Permissions::Write)){std::cerr<<"Framebuffer mapping failed\n";return false;}if(!memory.map(ZenithInputABI::Address,ZenithInputABI::Address,GuestMemory::PageSize,GuestMemory::Permissions::Read|GuestMemory::Permissions::Write)){std::cerr<<"Input ABI mapping failed\n";return false;}ElfLoader loader;ElfLoadResult result;std::string error;if(!loader.loadImage(image,memory,result,error)){std::cerr<<"ELF load error: "<<error<<'\n';return false;}if(!memory.map(stackBase,63ull*1024ull*1024ull,stackSize,GuestMemory::Permissions::Read|GuestMemory::Permissions::Write)){std::cerr<<"ELF stack mapping failed\n";return false;}cpu.setRegister(CPU::RSP,stackTop);cpu.setRip(result.entryPoint);std::cout<<"ELF loaded: entry = 0x"<<std::hex<<result.entryPoint<<", program headers = "<<std::dec<<result.programHeaders<<'\n';return true;}

static bool loadElf(const std::string& path,bool graphics,GuestMemory& memory,CPU& cpu){std::vector<std::uint8_t> image;if(!readFile(path,image))return false;return loadGuest(image,graphics,memory,cpu);}
static bool loadAppx(const std::string& path,bool graphics,GuestMemory& memory,CPU& cpu){AppxLoader loader;AppxLoadResult result;std::string error;if(!loader.loadFile(path,result,error)){std::cerr<<"APPX load error: "<<error<<'\n';return false;}std::cout<<"APPX loaded: "<<result.manifest.identityName<<" "<<result.manifest.version<<"\nExecutable: "<<result.executableName<<'\n';return loadGuest(result.executable,graphics,memory,cpu);}

static void publishInput(GuestMemory& memory,const InputState& input){const auto& c=input.controller();std::uint32_t buttons=0,dpad=0;if(c.buttonA)buttons|=ZenithInputABI::A;if(c.buttonB)buttons|=ZenithInputABI::B;if(c.buttonX)buttons|=ZenithInputABI::X;if(c.buttonY)buttons|=ZenithInputABI::Y;if(c.dpadUp)dpad|=ZenithInputABI::Up;if(c.dpadDown)dpad|=ZenithInputABI::Down;if(c.dpadLeft)dpad|=ZenithInputABI::Left;if(c.dpadRight)dpad|=ZenithInputABI::Right;memory.write32(ZenithInputABI::Address+0x00,ZenithInputABI::Magic);memory.write32(ZenithInputABI::Address+0x04,ZenithInputABI::Version);memory.write32(ZenithInputABI::Address+0x08,buttons);memory.write32(ZenithInputABI::Address+0x0C,dpad);std::uint32_t bits=0;std::memcpy(&bits,&c.leftStick.x,4);memory.write32(ZenithInputABI::Address+0x10,bits);std::memcpy(&bits,&c.leftStick.y,4);memory.write32(ZenithInputABI::Address+0x14,bits);std::memcpy(&bits,&c.rightStick.x,4);memory.write32(ZenithInputABI::Address+0x18,bits);std::memcpy(&bits,&c.rightStick.y,4);memory.write32(ZenithInputABI::Address+0x1C,bits);memory.write32(ZenithInputABI::Address+0x20,0);memory.write32(ZenithInputABI::Address+0x24,0);}

static int runHeadless(CPU& cpu){constexpr std::uint64_t maxInstructions=1'000'000;std::uint64_t executed=0;while(!cpu.halted()&&executed<maxInstructions){if(!cpu.step()){std::cerr<<"CPU error after ELF load at RIP 0x"<<std::hex<<cpu.rip()<<": "<<cpu.lastError()<<'\n';return 1;}++executed;}if(!cpu.halted()){std::cerr<<"ELF execution stopped after "<<maxInstructions<<" instructions (possible infinite loop).\n";return 1;}std::cout<<"\nELF exited with code "<<cpu.exitCode()<<" after "<<executed<<" instructions.\n";return static_cast<int>(cpu.exitCode());}

static int runGraphics(CPU& cpu,GuestMemory& memory,std::uint64_t fb,const std::string& initialTitle){constexpr int width=1280,height=720;constexpr int guestWidth=320,guestHeight=240;constexpr std::uint64_t instructionsPerFrame=100000;XenithWindow window(width,height,initialTitle.empty()?"Zenith - Xbox Series X|S Emulator":initialTitle.c_str());Renderer renderer(width,height);bool guestFinished=false;while(window.isOpen()){window.pollEvents();publishInput(memory,window.input());if(!guestFinished){cpu.clearFramePresented();for(std::uint64_t i=0;i<instructionsPerFrame&&!cpu.halted();++i){if(!cpu.step()){std::cerr<<"CPU error at RIP 0x"<<std::hex<<cpu.rip()<<": "<<cpu.lastError()<<'\n';return 1;}}if(cpu.halted()){guestFinished=true;std::cout<<"\nELF exited with code "<<cpu.exitCode()<<".\n";}}renderer.clear(0x00101018);if(!renderer.drawGuestFramebuffer(memory,fb,guestWidth,guestHeight)){std::cerr<<"Guest framebuffer read failed\n";return 1;}window.present(renderer.pixels(),renderer.width(),renderer.height());std::this_thread::sleep_for(std::chrono::milliseconds(16));}return static_cast<int>(cpu.exitCode());}

int main(int argc,char**argv){constexpr std::uint64_t fb=0x800000;std::cout<<"Zenith 0.3.0\nInitializing guest memory and x86-64 CPU...\n";const bool requestedElf=argc>=3&&(std::string(argv[1])=="--elf"||std::string(argv[1])=="--graphics");const bool requestedAppx=argc>=3&&(std::string(argv[1])=="--appx"||std::string(argv[1])=="--appx-graphics");const bool graphics=argc>=3&&(std::string(argv[1])=="--graphics"||std::string(argv[1])=="--appx-graphics");GuestMemory memory(64ull*1024ull*1024ull);if(requestedElf||requestedAppx){CPU cpu(memory);bool ok=requestedAppx?loadAppx(argv[2],graphics,memory,cpu):loadElf(argv[2],graphics,memory,cpu);if(!ok)return 1;if(graphics)return runGraphics(cpu,memory,fb,{});return runHeadless(cpu);}XenithWindow window(1280,720,"Zenith - Xbox Series X|S Emulator");Renderer renderer(1280,720);float angle=0;while(window.isOpen()){window.pollEvents();renderer.clear(0x00101018);renderer.drawCube(angle);window.present(renderer.pixels(),renderer.width(),renderer.height());angle+=0.01f;std::this_thread::sleep_for(std::chrono::milliseconds(16));}std::cout<<"Zenith shutting down.\n";return 0;}
