#include "appx_package.h"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <limits>
#include <zlib.h>
namespace {
std::uint16_t u16(const std::vector<std::uint8_t>& b,std::size_t p){return std::uint16_t(b[p])|(std::uint16_t(b[p+1])<<8);}
std::uint32_t u32(const std::vector<std::uint8_t>& b,std::size_t p){return std::uint32_t(b[p])|(std::uint32_t(b[p+1])<<8)|(std::uint32_t(b[p+2])<<16)|(std::uint32_t(b[p+3])<<24);}
std::string xmlAttr(const std::string& x,const std::string& key){std::size_t p=0;while((p=x.find(key,p))!=std::string::npos){std::size_t q=p+key.size();if(q<x.size()&&std::isspace(static_cast<unsigned char>(x[q]))){q=x.find('=',q);if(q==std::string::npos)return{};++q;while(q<x.size()&&std::isspace(static_cast<unsigned char>(x[q])))++q;if(q<x.size()&&(x[q]=='"'||x[q]=='\'')){char c=x[q++];auto e=x.find(c,q);if(e!=std::string::npos)return x.substr(q,e-q);}}p=q;}return{};}
}
bool AppxPackage::open(const std::string& path,std::string& error){close();std::ifstream f(path,std::ios::binary|std::ios::ate);if(!f){error="could not open APPX file";return false;}auto size=f.tellg();if(size<0||static_cast<unsigned long long>(size)>512ull*1024ull*1024ull){error="APPX is too large";return false;}archive_.resize(static_cast<std::size_t>(size));f.seekg(0);f.read(reinterpret_cast<char*>(archive_.data()),size);if(!f){error="could not read APPX file";close();return false;}path_=path;if(!parseCentralDirectory(error)){close();return false;}std::string xml;if(!readManifest(xml,error)||!parseManifest(xml,error)){close();return false;}return true;}
void AppxPackage::close(){path_.clear();archive_.clear();files_.clear();manifest_={};}
bool AppxPackage::isOpen()const{return !archive_.empty();}
bool AppxPackage::hasFile(const std::string& n)const{return std::any_of(files_.begin(),files_.end(),[&](const auto&e){return e.name==n;});}
bool AppxPackage::parseCentralDirectory(std::string& error){if(archive_.size()<22){error="not a valid ZIP/APPX archive";return false;}std::size_t start=archive_.size()>65557?archive_.size()-65557:0,eocd=std::numeric_limits<std::size_t>::max();for(std::size_t p=archive_.size()-22;p>=start;--p){if(u32(archive_,p)==0x06054b50){eocd=p;break;}if(p==0)break;}if(eocd==std::numeric_limits<std::size_t>::max()){error="ZIP end-of-central-directory not found";return false;}const std::uint16_t count=u16(archive_,eocd+10);const std::uint32_t cdSize=u32(archive_,eocd+12);const std::uint32_t cdOffset=u32(archive_,eocd+16);if(std::uint64_t(cdOffset)+cdSize>archive_.size()){error="invalid ZIP central directory";return false;}std::size_t p=cdOffset;for(std::uint32_t i=0;i<count;++i){if(p+46>archive_.size()||u32(archive_,p)!=0x02014b50){error="invalid ZIP central directory entry";return false;}const std::uint16_t method=u16(archive_,p+10);const std::uint32_t csize=u32(archive_,p+20);const std::uint32_t usize=u32(archive_,p+24);const std::uint16_t nlen=u16(archive_,p+28);const std::uint16_t xlen=u16(archive_,p+30);const std::uint16_t clen=u16(archive_,p+32);const std::uint32_t off=u32(archive_,p+42);if(p+46ull+nlen+xlen+clen>archive_.size()){error="truncated ZIP central directory entry";return false;}files_.push_back({std::string(reinterpret_cast<const char*>(&archive_[p+46]),nlen),csize,usize,off,method});p+=46ull+nlen+xlen+clen;}if(!hasFile("AppxManifest.xml")){error="APPX manifest not found";return false;}return true;}
bool AppxPackage::readFile(const std::string& name,std::vector<std::uint8_t>& data,std::string& error)const{auto it=std::find_if(files_.begin(),files_.end(),[&](const auto&e){return e.name==name;});if(it==files_.end()){error="APPX file not found: "+name;return false;}auto o=it->localHeaderOffset;if(o+30>archive_.size()||u32(archive_,o)!=0x04034b50){error="invalid local ZIP header";return false;}const auto nlen=u16(archive_,o+26);const auto xlen=u16(archive_,o+28);std::size_t start=o+30ull+nlen+xlen;if(start+it->compressedSize>archive_.size()){error="truncated APPX entry";return false;}if(it->method==0){data.assign(archive_.begin()+start,archive_.begin()+start+it->compressedSize);return data.size()==it->uncompressedSize;}if(it->method!=8){error="unsupported APPX compression method";return false;}if(it->uncompressedSize>512u*1024u*1024u){error="APPX entry is too large";return false;}data.resize(it->uncompressedSize);z_stream zs{};zs.next_in=const_cast<Bytef*>(reinterpret_cast<const Bytef*>(archive_.data()+start));zs.avail_in=it->compressedSize;zs.next_out=data.data();zs.avail_out=it->uncompressedSize;if(inflateInit2(&zs,-MAX_WBITS)!=Z_OK){error="could not initialize ZIP decompressor";return false;}int r=inflate(&zs,Z_FINISH);inflateEnd(&zs);if(r!=Z_STREAM_END||zs.total_out!=it->uncompressedSize){error="APPX entry decompression failed";return false;}return true;}
bool AppxPackage::readManifest(std::string& xml,std::string& error)const{std::vector<std::uint8_t>d;if(!readFile("AppxManifest.xml",d,error))return false;xml.assign(reinterpret_cast<const char*>(d.data()),d.size());return true;}
bool AppxPackage::parseManifest(const std::string& xml,std::string& error){manifest_.identityName=xmlAttr(xml,"Name");manifest_.publisher=xmlAttr(xml,"Publisher");manifest_.version=xmlAttr(xml,"Version");manifest_.displayName=xmlAttr(xml,"DisplayName");manifest_.description=xmlAttr(xml,"Description");manifest_.executable=xmlAttr(xml,"Executable");if(manifest_.identityName.empty()){error="APPX manifest has no Identity Name";return false;}return true;}
